var searchData=
[
  ['addanimator_0',['AddAnimator',['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animator_merger.html#a1c44af5f53c11742272acb7db94c1706',1,'Chocopoi::AvatarLib::Animations::AnimatorMerger']]],
  ['addanimatorparameter_1',['AddAnimatorParameter',['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animation_utils.html#ad4016bad61f9a8be15a28320ff7798aa',1,'Chocopoi.AvatarLib.Animations.AnimationUtils.AddAnimatorParameter(AnimatorController controller, string name, bool defaultValue)'],['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animation_utils.html#a20a9549438655cfc1a29786dcaaf4be2',1,'Chocopoi.AvatarLib.Animations.AnimationUtils.AddAnimatorParameter(AnimatorController controller, string name, int defaultValue)'],['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animation_utils.html#a64fce971f435ed46aacfd307a78d66eb',1,'Chocopoi.AvatarLib.Animations.AnimationUtils.AddAnimatorParameter(AnimatorController controller, string name, float defaultValue)']]],
  ['addbutton_2',['AddButton',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#af17c6abe939f01518dad9602e217696c',1,'Chocopoi::AvatarLib::Expressions::ExpressionMenuBuilder']]],
  ['addexpressionparameters_3',['AddExpressionParameters',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_utils.html#a91d0e9d658b021f1ab212830a9ee8bd0',1,'Chocopoi::AvatarLib::Expressions::ExpressionMenuUtils']]],
  ['addfouraxispuppet_4',['AddFourAxisPuppet',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a6248818c60edf53552d1b84be812a634',1,'Chocopoi.AvatarLib.Expressions.ExpressionMenuBuilder.AddFourAxisPuppet(string name, string upParameter, string rightParameter, string downParameter, string leftParameter, string upLabel, string rightLabel, string downLabel, string leftLabel, string parameterOnOpen=null, float valueOnOpen=1)'],['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a9173b91a337ec0053ceb33955e31983f',1,'Chocopoi.AvatarLib.Expressions.ExpressionMenuBuilder.AddFourAxisPuppet(string name, string upParameter, string rightParameter, string downParameter, string leftParameter, VRCExpressionsMenu.Control.Label upLabel, VRCExpressionsMenu.Control.Label rightLabel, VRCExpressionsMenu.Control.Label downLabel, VRCExpressionsMenu.Control.Label leftLabel, string parameterOnOpen=null, float valueOnOpen=1)']]],
  ['addradialpuppet_5',['AddRadialPuppet',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a0154c5f291455c87e10d8f23b1de384c',1,'Chocopoi::AvatarLib::Expressions::ExpressionMenuBuilder']]],
  ['addsubmenu_6',['AddSubMenu',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_utils.html#a71c1fca5db3150a448180896323a4cb2',1,'Chocopoi.AvatarLib.Expressions.ExpressionMenuUtils.AddSubMenu()'],['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a7c1db5e11a91610f78b2a940b2872bd5',1,'Chocopoi.AvatarLib.Expressions.ExpressionMenuBuilder.AddSubMenu(string name, VRCExpressionsMenu subMenu, Texture2D icon=null, string parameterOnOpen=null, float valueOnOpen=1)']]],
  ['addtoggle_7',['AddToggle',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a6bd51aebedd49ed9e02776cadb137e9b',1,'Chocopoi::AvatarLib::Expressions::ExpressionMenuBuilder']]],
  ['addtwoaxispuppet_8',['AddTwoAxisPuppet',['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a99e75c4a6c80faac0eb374ed01f6455d',1,'Chocopoi.AvatarLib.Expressions.ExpressionMenuBuilder.AddTwoAxisPuppet(string name, string horizontalParameter, string verticalParameter, string horizontalLabel, string verticalLabel, string parameterOnOpen=null, float valueOnOpen=1)'],['../class_chocopoi_1_1_avatar_lib_1_1_expressions_1_1_expression_menu_builder.html#a3dfafb7d41ef25db047d753f89aa7e17',1,'Chocopoi.AvatarLib.Expressions.ExpressionMenuBuilder.AddTwoAxisPuppet(string name, string horizontalParameter, string verticalParameter, VRCExpressionsMenu.Control.Label horizontalLabel, VRCExpressionsMenu.Control.Label verticalLabel, string parameterOnOpen=null, float valueOnOpen=1)']]],
  ['animationutils_9',['AnimationUtils',['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animation_utils.html',1,'Chocopoi::AvatarLib::Animations']]],
  ['animationutils_2ecs_10',['AnimationUtils.cs',['../_animation_utils_8cs.html',1,'']]],
  ['animatormerger_11',['AnimatorMerger',['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animator_merger.html#a917b52d49311da2cd41392fdc1a330bc',1,'Chocopoi.AvatarLib.Animations.AnimatorMerger.AnimatorMerger()'],['../class_chocopoi_1_1_avatar_lib_1_1_animations_1_1_animator_merger.html',1,'Chocopoi.AvatarLib.Animations.AnimatorMerger']]],
  ['animatormerger_2ecs_12',['AnimatorMerger.cs',['../_animator_merger_8cs.html',1,'']]]
];
